import React, { useState, useEffect } from "react";
import axios from "axios";
import Head from "next/head";
import { FaInstagram, FaTwitter, FaYoutube } from "react-icons/fa";
import { MdLocalShipping } from "react-icons/md";
import Layout from "../../components/Layout";
import { useRouter } from "next/router";

import {
  Box,
  useColorModeValue,
  Heading,
  Text,
  Stack,
  Container,
  Image,
  Flex,
  VStack,
  Button,
  SimpleGrid,
  StackDivider,
  List,
  ListItem,
  Center,
  Spinner,
  Tag,
  HStack,
} from "@chakra-ui/react";
const IMAGE =
  "https://suplar.com/wp-content/uploads/2021/11/ProfilePixNathaniel2-300x300.png";

let fetchData = async (authorId) => {
  const response = await fetch(`https://reqres.in/api/users/${authorId}`);
  const data = await response.json();
  return data.data;
};

export default function Dao() {
  const router = useRouter();
  const { dao, daoId } = router.query;
  const [isLoading, setLoading] = useState(true);
  const [daoInfo, setDao] = useState([]);
  //   if (!isLoading) {
  //     let tags = daoInfo.tags.slice(0, 5);
  //   }

  useEffect(() => {
    axios
      .get(
        `https://daoproxyapi.herokuapp.com/daos/${daoId}`
        //   {
        //     params: { daoId: daoId },
        //   }
      )
      .then((response) => {
        console.log("dao", daoInfo);
        setDao(response.data.data[daoId]);
        setLoading(false);
      });
  }, []);

  if (isLoading) {
    return (
      <Center bg="#fff" height="100vh" color="white">
        <Spinner
          thickness="4px"
          speed="0.35s"
          emptyColor="gray.200"
          color="pink.500"
          size="xl"
        />
      </Center>
    );
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Container maxW={"7xl"}>
          <SimpleGrid
            columns={{ base: 1, lg: 2 }}
            spacing={{ base: 8, md: 10 }}
            py={{ base: 18, md: 24 }}
          >
            <Stack spacing={{ base: 6, md: 10 }}>
              <Box as={"header"}>
                <Heading
                  lineHeight={1.1}
                  fontWeight={600}
                  fontSize={{ base: "2xl", sm: "4xl", lg: "5xl" }}
                >
                  <Image
                    borderRadius="full"
                    boxSize="64px"
                    src={daoInfo.logo}
                    alt={daoInfo.name}
                  />
                </Heading>
                <Text
                  color={useColorModeValue("gray.900", "gray.400")}
                  fontWeight={300}
                  fontSize={"2xl"}
                ></Text>
              </Box>

              <Stack
                spacing={{ base: 4, sm: 6 }}
                direction={"column"}
                divider={
                  <StackDivider
                    borderColor={useColorModeValue("gray.200", "gray.600")}
                  />
                }
              >
                {/* <VStack spacing={{ base: 4, sm: 6 }}>
                  <Text
                    color={useColorModeValue("gray.500", "gray.400")}
                    fontSize={"2xl"}
                    fontWeight={"300"}
                  >
                    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed
                    diam nonumy eirmod tempor invidunt ut labore
                  </Text>
                  <Text fontSize={"lg"}>{daoInfo.description}</Text>
                </VStack> */}
                <Box>
                  <Text
                    fontSize={{ base: "16px", lg: "18px" }}
                    color={useColorModeValue("yellow.500", "yellow.300")}
                    fontWeight={"500"}
                    textTransform={"uppercase"}
                    mb={"4"}
                  >
                    Platform
                  </Text>

                  <SimpleGrid columns={{ base: 1, md: 2 }} spacing={10}>
                    <List spacing={2}>
                      <ListItem>Chain</ListItem>
                      <ListItem>Symbol</ListItem>{" "}
                      <ListItem>Token Address</ListItem>
                    </List>
                    <List spacing={2}>
                      <ListItem>
                        {daoInfo.platform && daoInfo.platform.name}
                      </ListItem>
                      <ListItem>
                        {daoInfo.platform && daoInfo.platform.symbol}
                      </ListItem>
                      <ListItem>
                        {daoInfo.platform && daoInfo.platform.token_address}
                      </ListItem>
                    </List>
                  </SimpleGrid>
                </Box>
                <Box>
                  <Text
                    fontSize={{ base: "16px", lg: "18px" }}
                    color={useColorModeValue("yellow.500", "yellow.300")}
                    fontWeight={"500"}
                    textTransform={"uppercase"}
                    mb={"4"}
                  >
                    Online
                  </Text>

                  <List spacing={2}>
                    <ListItem>
                      <Text as={"span"} fontWeight={"bold"}>
                        Website:
                      </Text>{" "}
                      {daoInfo.urls.website[0]}
                    </ListItem>
                    <ListItem>
                      <Text as={"span"} fontWeight={"bold"}>
                        Twitter:
                      </Text>{" "}
                      {daoInfo.urls.twitter[0]}
                    </ListItem>
                    <ListItem>
                      <Text as={"span"} fontWeight={"bold"}>
                        Reddit
                      </Text>{" "}
                      {daoInfo.urls.reddit[0]}
                    </ListItem>
                    <hr />
                    <ListItem>
                      <Text as={"span"} fontWeight={"bold"}>
                        Documentation:
                      </Text>{" "}
                      {daoInfo.urls.technical_doc[0]}
                    </ListItem>
                    <ListItem>
                      <Text as={"span"} fontWeight={"bold"}>
                        Explorer:
                      </Text>{" "}
                      {daoInfo.urls.explorer[0]}
                    </ListItem>
                  </List>
                </Box>
              </Stack>

              <Button
                href={daoInfo.urls.website[0]}
                target="_blank"
                rounded={"none"}
                w={"full"}
                mt={8}
                size={"lg"}
                py={"7"}
                bg={useColorModeValue("gray.900", "gray.50")}
                color={useColorModeValue("white", "gray.900")}
                textTransform={"uppercase"}
                _hover={{
                  transform: "translateY(2px)",
                  boxShadow: "lg",
                }}
              >
                Visit Website
              </Button>

              <Stack
                direction="row"
                alignItems="center"
                justifyContent={"center"}
              >
                <Text></Text>
              </Stack>
            </Stack>
            <Stack spacing={{ base: 6, md: 10 }}>
              <Box as={"header"}>
                <Heading
                  lineHeight={1.1}
                  fontWeight={600}
                  fontSize={{ base: "2xl", sm: "4xl", lg: "5xl" }}
                >
                  {daoInfo.name}
                </Heading>
                <Text
                  color={useColorModeValue("gray.900", "gray.400")}
                  fontWeight={300}
                  fontSize={"2xl"}
                >
                  $350.00 USD
                </Text>
              </Box>

              <Stack
                spacing={{ base: 4, sm: 6 }}
                direction={"column"}
                divider={
                  <StackDivider
                    borderColor={useColorModeValue("gray.200", "gray.600")}
                  />
                }
              >
                <VStack spacing={{ base: 4, sm: 6 }}>
                  <Text
                    color={useColorModeValue("gray.500", "gray.400")}
                    fontSize={"2xl"}
                    fontWeight={"300"}
                  >
                    <HStack spacing={4}>
                      <Tag
                        size="md"
                        key="md"
                        variant="solid"
                        colorScheme="teal"
                      >
                        {daoInfo.tags[0]}
                      </Tag>
                      <Tag
                        size="md"
                        key="md"
                        variant="solid"
                        colorScheme="teal"
                      >
                        {daoInfo.tags[1]}
                      </Tag>
                      <Tag
                        size="md"
                        key="md"
                        variant="solid"
                        colorScheme="teal"
                      >
                        {daoInfo.tags[2]}
                      </Tag>
                      <Tag
                        size="md"
                        key="md"
                        variant="solid"
                        colorScheme="teal"
                      >
                        {daoInfo.tags[3]}
                      </Tag>
                      <Tag
                        size="md"
                        key="md"
                        variant="solid"
                        colorScheme="teal"
                      >
                        {daoInfo.tags[4]}
                      </Tag>
                    </HStack>
                    {/* {daoInfo.tags.map((tag, index) => ({ tag }))} */}
                  </Text>
                  <Text fontSize={"lg"}>{daoInfo.description}</Text>
                </VStack>
                <Box>
                  <Text
                    fontSize={{ base: "16px", lg: "18px" }}
                    color={useColorModeValue("yellow.500", "yellow.300")}
                    fontWeight={"500"}
                    textTransform={"uppercase"}
                    mb={"4"}
                  >
                    Market
                  </Text>

                  <SimpleGrid columns={{ base: 1, md: 2 }} spacing={10}>
                    <List spacing={2}>
                      <ListItem>Circulating supply</ListItem>
                      <ListItem>Market cap</ListItem>{" "}
                      {/* <ListItem>Tachymeter</ListItem> */}
                    </List>
                    <List spacing={2}>
                      <ListItem>
                        $
                        {daoInfo.self_reported_circulating_supply &&
                          daoInfo.self_reported_circulating_supply
                            .toFixed(2)
                            .replace(/\d(?=(\d{3})+\.)/g, "$&,")}
                      </ListItem>
                      <ListItem>
                        $
                        {daoInfo.self_reported_market_cap &&
                          daoInfo.self_reported_market_cap
                            .toFixed(2)
                            .replace(/\d(?=(\d{3})+\.)/g, "$&,")}
                      </ListItem>
                      {/* <ListItem>Small seconds</ListItem> */}
                    </List>
                  </SimpleGrid>
                </Box>
                <Box>
                  <Text
                    fontSize={{ base: "16px", lg: "18px" }}
                    color={useColorModeValue("yellow.500", "yellow.300")}
                    fontWeight={"500"}
                    textTransform={"uppercase"}
                    mb={"4"}
                  >
                    Product Details
                  </Text>

                  <List spacing={2}>
                    <ListItem>
                      <Text as={"span"} fontWeight={"bold"}>
                        Between lugs:
                      </Text>{" "}
                      20 mm
                    </ListItem>
                    <ListItem>
                      <Text as={"span"} fontWeight={"bold"}>
                        Bracelet:
                      </Text>{" "}
                      leather strap
                    </ListItem>
                    <ListItem>
                      <Text as={"span"} fontWeight={"bold"}>
                        Case:
                      </Text>{" "}
                      Steel
                    </ListItem>
                    <ListItem>
                      <Text as={"span"} fontWeight={"bold"}>
                        Case diameter:
                      </Text>{" "}
                      42 mm
                    </ListItem>
                    <ListItem>
                      <Text as={"span"} fontWeight={"bold"}>
                        Dial color:
                      </Text>{" "}
                      Black
                    </ListItem>
                    <ListItem>
                      <Text as={"span"} fontWeight={"bold"}>
                        Crystal:
                      </Text>{" "}
                      Domed, scratch‑resistant sapphire crystal with
                      anti‑reflective treatment inside
                    </ListItem>
                    <ListItem>
                      <Text as={"span"} fontWeight={"bold"}>
                        Water resistance:
                      </Text>{" "}
                      5 bar (50 metres / 167 feet){" "}
                    </ListItem>
                  </List>
                </Box>
              </Stack>

              <Button
                rounded={"none"}
                w={"full"}
                mt={8}
                size={"lg"}
                py={"7"}
                bg={useColorModeValue("gray.900", "gray.50")}
                color={useColorModeValue("white", "gray.900")}
                textTransform={"uppercase"}
                _hover={{
                  transform: "translateY(2px)",
                  boxShadow: "lg",
                }}
              >
                Add to cart
              </Button>

              <Stack
                direction="row"
                alignItems="center"
                justifyContent={"center"}
              >
                <MdLocalShipping />
                <Text>2-3 business days delivery</Text>
              </Stack>
            </Stack>
          </SimpleGrid>
        </Container>
        {/* {daoInfo.description}
        <img src={daoInfo.logo} />
        {daoId} */}
      </Layout>
    </div>
  );
}

// import {
//     Box,
//     chakra,
//     Container,
//     Stack,
//     Text,
//     Image,
//     Flex,
//     VStack,
//     Button,
//     Heading,
//     SimpleGrid,
//     StackDivider,
//     useColorModeValue,
//     VisuallyHidden,
//     List,
//     ListItem,
//   } from '@chakra-ui/react';
//   import { FaInstagram, FaTwitter, FaYoutube } from 'react-icons/fa';
//   import { MdLocalShipping } from 'react-icons/md';

//   export default function Simple() {
//     return (
//       <Container maxW={'7xl'}>
//         <SimpleGrid
//           columns={{ base: 1, lg: 2 }}
//           spacing={{ base: 8, md: 10 }}
//           py={{ base: 18, md: 24 }}>
//           <Flex>
//             <Image
//               rounded={'md'}
//               alt={'product image'}
//               src={
//                 'https://images.unsplash.com/photo-1596516109370-29001ec8ec36?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwyODE1MDl8MHwxfGFsbHx8fHx8fHx8fDE2Mzg5MzY2MzE&ixlib=rb-1.2.1&q=80&w=1080'
//               }
//               fit={'cover'}
//               align={'center'}
//               w={'100%'}
//               h={{ base: '100%', sm: '400px', lg: '500px' }}
//             />
//           </Flex>
//           <Stack spacing={{ base: 6, md: 10 }}>
//             <Box as={'header'}>
//               <Heading
//                 lineHeight={1.1}
//                 fontWeight={600}
//                 fontSize={{ base: '2xl', sm: '4xl', lg: '5xl' }}>
//                 Automatic Watch
//               </Heading>
//               <Text
//                 color={useColorModeValue('gray.900', 'gray.400')}
//                 fontWeight={300}
//                 fontSize={'2xl'}>
//                 $350.00 USD
//               </Text>
//             </Box>

//             <Stack
//               spacing={{ base: 4, sm: 6 }}
//               direction={'column'}
//               divider={
//                 <StackDivider
//                   borderColor={useColorModeValue('gray.200', 'gray.600')}
//                 />
//               }>
//               <VStack spacing={{ base: 4, sm: 6 }}>
//                 <Text
//                   color={useColorModeValue('gray.500', 'gray.400')}
//                   fontSize={'2xl'}
//                   fontWeight={'300'}>
//                   Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed
//                   diam nonumy eirmod tempor invidunt ut labore
//                 </Text>
//                 <Text fontSize={'lg'}>
//                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad
//                   aliquid amet at delectus doloribus dolorum expedita hic, ipsum
//                   maxime modi nam officiis porro, quae, quisquam quos
//                   reprehenderit velit? Natus, totam.
//                 </Text>
//               </VStack>
//               <Box>
//                 <Text
//                   fontSize={{ base: '16px', lg: '18px' }}
//                   color={useColorModeValue('yellow.500', 'yellow.300')}
//                   fontWeight={'500'}
//                   textTransform={'uppercase'}
//                   mb={'4'}>
//                   Features
//                 </Text>

//                 <SimpleGrid columns={{ base: 1, md: 2 }} spacing={10}>
//                   <List spacing={2}>
//                     <ListItem>Chronograph</ListItem>
//                     <ListItem>Master Chronometer Certified</ListItem>{' '}
//                     <ListItem>Tachymeter</ListItem>
//                   </List>
//                   <List spacing={2}>
//                     <ListItem>Anti‑magnetic</ListItem>
//                     <ListItem>Chronometer</ListItem>
//                     <ListItem>Small seconds</ListItem>
//                   </List>
//                 </SimpleGrid>
//               </Box>
//               <Box>
//                 <Text
//                   fontSize={{ base: '16px', lg: '18px' }}
//                   color={useColorModeValue('yellow.500', 'yellow.300')}
//                   fontWeight={'500'}
//                   textTransform={'uppercase'}
//                   mb={'4'}>
//                   Product Details
//                 </Text>

//                 <List spacing={2}>
//                   <ListItem>
//                     <Text as={'span'} fontWeight={'bold'}>
//                       Between lugs:
//                     </Text>{' '}
//                     20 mm
//                   </ListItem>
//                   <ListItem>
//                     <Text as={'span'} fontWeight={'bold'}>
//                       Bracelet:
//                     </Text>{' '}
//                     leather strap
//                   </ListItem>
//                   <ListItem>
//                     <Text as={'span'} fontWeight={'bold'}>
//                       Case:
//                     </Text>{' '}
//                     Steel
//                   </ListItem>
//                   <ListItem>
//                     <Text as={'span'} fontWeight={'bold'}>
//                       Case diameter:
//                     </Text>{' '}
//                     42 mm
//                   </ListItem>
//                   <ListItem>
//                     <Text as={'span'} fontWeight={'bold'}>
//                       Dial color:
//                     </Text>{' '}
//                     Black
//                   </ListItem>
//                   <ListItem>
//                     <Text as={'span'} fontWeight={'bold'}>
//                       Crystal:
//                     </Text>{' '}
//                     Domed, scratch‑resistant sapphire crystal with anti‑reflective
//                     treatment inside
//                   </ListItem>
//                   <ListItem>
//                     <Text as={'span'} fontWeight={'bold'}>
//                       Water resistance:
//                     </Text>{' '}
//                     5 bar (50 metres / 167 feet){' '}
//                   </ListItem>
//                 </List>
//               </Box>
//             </Stack>

//             <Button
//               rounded={'none'}
//               w={'full'}
//               mt={8}
//               size={'lg'}
//               py={'7'}
//               bg={useColorModeValue('gray.900', 'gray.50')}
//               color={useColorModeValue('white', 'gray.900')}
//               textTransform={'uppercase'}
//               _hover={{
//                 transform: 'translateY(2px)',
//                 boxShadow: 'lg',
//               }}>
//               Add to cart
//             </Button>

//             <Stack direction="row" alignItems="center" justifyContent={'center'}>
//               <MdLocalShipping />
//               <Text>2-3 business days delivery</Text>
//             </Stack>
//           </Stack>
//         </SimpleGrid>
//       </Container>
//     );
//   }
