import React, { useState } from "react";
import Head from "next/head";
import { SiLinkedin, SiTwitter } from "react-icons/si";
import Layout from "../../components/Layout";
import {
  Heading,
  Text,
  Flex,
  IconButton,
  Table,
  Thead,
  Tbody,
  Tr,
  Th,
  Td,
  Divider,
  Avatar,
} from "@chakra-ui/react";

import { FiCalendar, FiChevronDown, FiChevronUp } from "react-icons/fi";
const IMAGE =
  "https://suplar.com/wp-content/uploads/2021/11/ProfilePixNathaniel2-300x300.png";

export default function Daos() {
  const [display, changeDisplay] = useState("hide");

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Flex
          w={["100%", "100%", "100%", "100%", "100%"]}
          p="3%"
          flexDir="column"
          overflow="auto"
          minH="50vh"
          maxW="1200px"
          mx="auto"
        >
          <Flex justifyContent="space-between" mt={8}>
            <Flex align="flex-end">
              <Heading as="h2" size="lg" letterSpacing="tight">
                DAOs
              </Heading>
              <Text fontSize="small" color="gray" ml={4}>
                Apr 2021
              </Text>
            </Flex>
            <IconButton icon={<FiCalendar />} />
          </Flex>
          <Flex flexDir="column">
            <Flex overflow="auto">
              <Table variant="unstyled" mt={4}>
                <Thead>
                  <Tr color="gray">
                    <Th>Name of DAO</Th>
                    <Th>Category</Th>
                    <Th isNumeric>Membership</Th>
                    <Th isNumeric>Treasury Balance</Th>
                  </Tr>
                </Thead>
                <Tbody>
                  <Tr>
                    <Td>
                      <Flex align="center">
                        <Avatar
                          size="sm"
                          mr={2}
                          src="https://s2.coinmarketcap.com/static/img/coins/64x64/11221.png"
                        />
                        <Flex flexDir="column">
                          <Heading size="sm" letterSpacing="tight">
                            bitdao
                          </Heading>
                          <Text fontSize="sm" color="gray">
                            Apr 24, 2021 at 1:40pm
                          </Text>
                        </Flex>
                      </Flex>
                    </Td>
                    <Td>Electronic Devices</Td>
                    <Td isNumeric>+$2</Td>
                    <Td isNumeric>
                      <Text fontWeight="bold" display="inline-table">
                        $1,980,299,036
                      </Text>
                      .00
                    </Td>
                  </Tr>
                  <Tr>
                    <Td>
                      <Flex align="center">
                        <Avatar
                          size="sm"
                          mr={2}
                          src="https://s2.coinmarketcap.com/static/img/coins/64x64/7083.png"
                        />
                        <Flex flexDir="column">
                          <Heading size="sm" letterSpacing="tight">
                            Uniswap
                          </Heading>
                          <Text fontSize="sm" color="gray">
                            Apr 22, 2021 at 2:43pm
                          </Text>
                        </Flex>
                      </Flex>
                    </Td>
                    <Td>DEX</Td>
                    <Td isNumeric>+$23</Td>
                    <Td isNumeric>
                      <Text fontWeight="bold" display="inline-table">
                        -$32
                      </Text>
                      .00
                    </Td>
                  </Tr>
                  <Tr>
                    <Td>
                      <Flex align="center">
                        <Avatar
                          size="sm"
                          mr={2}
                          src="https://s2.coinmarketcap.com/static/img/coins/64x64/7278.png"
                        />
                        <Flex flexDir="column">
                          <Heading size="sm" letterSpacing="tight">
                            Aave
                          </Heading>
                          <Text fontSize="sm" color="gray">
                            Apr 13, 2021 at 11:23am
                          </Text>
                        </Flex>
                      </Flex>
                    </Td>
                    <Td>DeFi</Td>
                    <Td isNumeric>+$4</Td>
                    <Td isNumeric>
                      <Text fontWeight="bold" display="inline-table">
                        -$112
                      </Text>
                      .00
                    </Td>
                  </Tr>
                  {/* {display == "show" && (
                    <> */}
                  <Tr>
                    <Td>
                      <Flex align="center">
                        <Avatar
                          size="sm"
                          mr={2}
                          src="https://s2.coinmarketcap.com/static/img/coins/64x64/1518.png"
                        />
                        <Flex flexDir="column">
                          <Heading size="sm" letterSpacing="tight">
                            Maker
                          </Heading>
                          <Text fontSize="sm" color="gray">
                            Apr 12, 2021 at 9:40pm
                          </Text>
                        </Flex>
                      </Flex>
                    </Td>
                    <Td>DeFi</Td>
                    <Td isNumeric>+$2</Td>
                    <Td isNumeric>
                      <Text fontWeight="bold" display="inline-table">
                        -$242
                      </Text>
                      .00
                    </Td>
                  </Tr>
                  <Tr>
                    <Td>
                      <Flex align="center">
                        <Avatar
                          size="sm"
                          mr={2}
                          src="https://s2.coinmarketcap.com/static/img/coins/64x64/6538.png"
                        />
                        <Flex flexDir="column">
                          <Heading size="sm" letterSpacing="tight">
                            Curve
                          </Heading>
                          <Text fontSize="sm" color="gray">
                            Apr 10, 2021 at 2:10pm
                          </Text>
                        </Flex>
                      </Flex>
                    </Td>
                    <Td>DeFi</Td>
                    <Td isNumeric>+$23</Td>
                    <Td isNumeric>
                      <Text fontWeight="bold" display="inline-table">
                        -$32
                      </Text>
                      .00
                    </Td>
                  </Tr>
                  <Tr>
                    <Td>
                      <Flex align="center">
                        <Avatar
                          size="sm"
                          mr={2}
                          src="https://s2.coinmarketcap.com/static/img/coins/64x64/131.png"
                        />
                        <Flex flexDir="column">
                          <Heading size="sm" letterSpacing="tight">
                            Dash
                          </Heading>
                          <Text fontSize="sm" color="gray">
                            Apr 7, 2021 at 9:03am
                          </Text>
                        </Flex>
                      </Flex>
                    </Td>
                    <Td>Social Media</Td>
                    <Td isNumeric>+$4</Td>
                    <Td isNumeric>
                      <Text fontWeight="bold" display="inline-table">
                        -$112
                      </Text>
                      .00
                    </Td>
                  </Tr>
                  {/* </>
                  )} */}
                </Tbody>
              </Table>
            </Flex>
            <Flex align="center">
              <Divider />
              <IconButton
                icon={display == "show" ? <FiChevronUp /> : <FiChevronDown />}
                onClick={() => {
                  if (display == "show") {
                    changeDisplay("none");
                  } else {
                    changeDisplay("show");
                  }
                }}
              />
              <Divider />
            </Flex>
          </Flex>
        </Flex>
      </Layout>
    </div>
  );
}
